// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: proto/app.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Intents_Intent int32

const (
	Intents_NONE       Intents_Intent = 0
	Intents_JUMP       Intents_Intent = 1
	Intents_MOVE_LEFT  Intents_Intent = 2
	Intents_MOVE_RIGHT Intents_Intent = 3
)

// Enum value maps for Intents_Intent.
var (
	Intents_Intent_name = map[int32]string{
		0: "NONE",
		1: "JUMP",
		2: "MOVE_LEFT",
		3: "MOVE_RIGHT",
	}
	Intents_Intent_value = map[string]int32{
		"NONE":       0,
		"JUMP":       1,
		"MOVE_LEFT":  2,
		"MOVE_RIGHT": 3,
	}
)

func (x Intents_Intent) Enum() *Intents_Intent {
	p := new(Intents_Intent)
	*p = x
	return p
}

func (x Intents_Intent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Intents_Intent) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_app_proto_enumTypes[0].Descriptor()
}

func (Intents_Intent) Type() protoreflect.EnumType {
	return &file_proto_app_proto_enumTypes[0]
}

func (x Intents_Intent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Intents_Intent.Descriptor instead.
func (Intents_Intent) EnumDescriptor() ([]byte, []int) {
	return file_proto_app_proto_rawDescGZIP(), []int{4, 0}
}

type Vector struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float64 `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float64 `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Vector) Reset() {
	*x = Vector{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_app_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector) ProtoMessage() {}

func (x *Vector) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector.ProtoReflect.Descriptor instead.
func (*Vector) Descriptor() ([]byte, []int) {
	return file_proto_app_proto_rawDescGZIP(), []int{0}
}

func (x *Vector) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Velocity *Vector  `protobuf:"bytes,2,opt,name=velocity,proto3" json:"velocity,omitempty"`
	Position *Vector  `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Intents  *Intents `protobuf:"bytes,4,opt,name=intents,proto3" json:"intents,omitempty"`
	Angle    float64  `protobuf:"fixed64,5,opt,name=angle,proto3" json:"angle,omitempty"`
}

func (x *Player) Reset() {
	*x = Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_app_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_proto_app_proto_rawDescGZIP(), []int{1}
}

func (x *Player) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Player) GetVelocity() *Vector {
	if x != nil {
		return x.Velocity
	}
	return nil
}

func (x *Player) GetPosition() *Vector {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Player) GetIntents() *Intents {
	if x != nil {
		return x.Intents
	}
	return nil
}

func (x *Player) GetAngle() float64 {
	if x != nil {
		return x.Angle
	}
	return 0
}

type State struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tick         int64     `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	PlayerStates []*Player `protobuf:"bytes,2,rep,name=player_states,json=playerStates,proto3" json:"player_states,omitempty"`
}

func (x *State) Reset() {
	*x = State{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_app_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_proto_app_proto_rawDescGZIP(), []int{2}
}

func (x *State) GetTick() int64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *State) GetPlayerStates() []*Player {
	if x != nil {
		return x.PlayerStates
	}
	return nil
}

type StateBuffer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	States       []*State       `protobuf:"bytes,1,rep,name=states,proto3" json:"states,omitempty"`
	FutureEvents []*ServerEvent `protobuf:"bytes,2,rep,name=future_events,json=futureEvents,proto3" json:"future_events,omitempty"`
	MaxCapacity  int64          `protobuf:"varint,3,opt,name=max_capacity,json=maxCapacity,proto3" json:"max_capacity,omitempty"`
}

func (x *StateBuffer) Reset() {
	*x = StateBuffer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_app_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateBuffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateBuffer) ProtoMessage() {}

func (x *StateBuffer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateBuffer.ProtoReflect.Descriptor instead.
func (*StateBuffer) Descriptor() ([]byte, []int) {
	return file_proto_app_proto_rawDescGZIP(), []int{3}
}

func (x *StateBuffer) GetStates() []*State {
	if x != nil {
		return x.States
	}
	return nil
}

func (x *StateBuffer) GetFutureEvents() []*ServerEvent {
	if x != nil {
		return x.FutureEvents
	}
	return nil
}

func (x *StateBuffer) GetMaxCapacity() int64 {
	if x != nil {
		return x.MaxCapacity
	}
	return 0
}

type Intents struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Intents []Intents_Intent `protobuf:"varint,1,rep,packed,name=intents,proto3,enum=Intents_Intent" json:"intents,omitempty"`
}

func (x *Intents) Reset() {
	*x = Intents{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_app_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Intents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Intents) ProtoMessage() {}

func (x *Intents) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Intents.ProtoReflect.Descriptor instead.
func (*Intents) Descriptor() ([]byte, []int) {
	return file_proto_app_proto_rawDescGZIP(), []int{4}
}

func (x *Intents) GetIntents() []Intents_Intent {
	if x != nil {
		return x.Intents
	}
	return nil
}

type Connect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Connect) Reset() {
	*x = Connect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_app_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Connect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connect) ProtoMessage() {}

func (x *Connect) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connect.ProtoReflect.Descriptor instead.
func (*Connect) Descriptor() ([]byte, []int) {
	return file_proto_app_proto_rawDescGZIP(), []int{5}
}

type RequestState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RequestState) Reset() {
	*x = RequestState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_app_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestState) ProtoMessage() {}

func (x *RequestState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestState.ProtoReflect.Descriptor instead.
func (*RequestState) Descriptor() ([]byte, []int) {
	return file_proto_app_proto_rawDescGZIP(), []int{6}
}

type Shoot struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Shoot) Reset() {
	*x = Shoot{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_app_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Shoot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shoot) ProtoMessage() {}

func (x *Shoot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shoot.ProtoReflect.Descriptor instead.
func (*Shoot) Descriptor() ([]byte, []int) {
	return file_proto_app_proto_rawDescGZIP(), []int{7}
}

func (x *Shoot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AddPlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddPlayer) Reset() {
	*x = AddPlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_app_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPlayer) ProtoMessage() {}

func (x *AddPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPlayer.ProtoReflect.Descriptor instead.
func (*AddPlayer) Descriptor() ([]byte, []int) {
	return file_proto_app_proto_rawDescGZIP(), []int{8}
}

type RemovePlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemovePlayer) Reset() {
	*x = RemovePlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_app_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemovePlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePlayer) ProtoMessage() {}

func (x *RemovePlayer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePlayer.ProtoReflect.Descriptor instead.
func (*RemovePlayer) Descriptor() ([]byte, []int) {
	return file_proto_app_proto_rawDescGZIP(), []int{9}
}

type Angle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Angle float64 `protobuf:"fixed64,1,opt,name=angle,proto3" json:"angle,omitempty"`
}

func (x *Angle) Reset() {
	*x = Angle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_app_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Angle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Angle) ProtoMessage() {}

func (x *Angle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Angle.ProtoReflect.Descriptor instead.
func (*Angle) Descriptor() ([]byte, []int) {
	return file_proto_app_proto_rawDescGZIP(), []int{10}
}

func (x *Angle) GetAngle() float64 {
	if x != nil {
		return x.Angle
	}
	return 0
}

type PlayerDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tick int64  `protobuf:"varint,2,opt,name=tick,proto3" json:"tick,omitempty"`
}

func (x *PlayerDetails) Reset() {
	*x = PlayerDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_app_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerDetails) ProtoMessage() {}

func (x *PlayerDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerDetails.ProtoReflect.Descriptor instead.
func (*PlayerDetails) Descriptor() ([]byte, []int) {
	return file_proto_app_proto_rawDescGZIP(), []int{11}
}

func (x *PlayerDetails) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlayerDetails) GetTick() int64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

type ClientEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tick int64  `protobuf:"varint,2,opt,name=tick,proto3" json:"tick,omitempty"`
	// Types that are assignable to Event:
	//	*ClientEvent_Connect
	//	*ClientEvent_Intents
	//	*ClientEvent_RequestState
	//	*ClientEvent_Angle
	//	*ClientEvent_Shoot
	Event isClientEvent_Event `protobuf_oneof:"event"`
}

func (x *ClientEvent) Reset() {
	*x = ClientEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_app_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEvent) ProtoMessage() {}

func (x *ClientEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEvent.ProtoReflect.Descriptor instead.
func (*ClientEvent) Descriptor() ([]byte, []int) {
	return file_proto_app_proto_rawDescGZIP(), []int{12}
}

func (x *ClientEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClientEvent) GetTick() int64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (m *ClientEvent) GetEvent() isClientEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *ClientEvent) GetConnect() *Connect {
	if x, ok := x.GetEvent().(*ClientEvent_Connect); ok {
		return x.Connect
	}
	return nil
}

func (x *ClientEvent) GetIntents() *Intents {
	if x, ok := x.GetEvent().(*ClientEvent_Intents); ok {
		return x.Intents
	}
	return nil
}

func (x *ClientEvent) GetRequestState() *RequestState {
	if x, ok := x.GetEvent().(*ClientEvent_RequestState); ok {
		return x.RequestState
	}
	return nil
}

func (x *ClientEvent) GetAngle() *Angle {
	if x, ok := x.GetEvent().(*ClientEvent_Angle); ok {
		return x.Angle
	}
	return nil
}

func (x *ClientEvent) GetShoot() *Shoot {
	if x, ok := x.GetEvent().(*ClientEvent_Shoot); ok {
		return x.Shoot
	}
	return nil
}

type isClientEvent_Event interface {
	isClientEvent_Event()
}

type ClientEvent_Connect struct {
	Connect *Connect `protobuf:"bytes,3,opt,name=connect,proto3,oneof"`
}

type ClientEvent_Intents struct {
	Intents *Intents `protobuf:"bytes,4,opt,name=intents,proto3,oneof"`
}

type ClientEvent_RequestState struct {
	RequestState *RequestState `protobuf:"bytes,5,opt,name=request_state,json=requestState,proto3,oneof"`
}

type ClientEvent_Angle struct {
	Angle *Angle `protobuf:"bytes,6,opt,name=angle,proto3,oneof"`
}

type ClientEvent_Shoot struct {
	Shoot *Shoot `protobuf:"bytes,7,opt,name=shoot,proto3,oneof"`
}

func (*ClientEvent_Connect) isClientEvent_Event() {}

func (*ClientEvent_Intents) isClientEvent_Event() {}

func (*ClientEvent_RequestState) isClientEvent_Event() {}

func (*ClientEvent_Angle) isClientEvent_Event() {}

func (*ClientEvent_Shoot) isClientEvent_Event() {}

type ServerEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tick   int64          `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	Player *PlayerDetails `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"`
	// Types that are assignable to Event:
	//	*ServerEvent_AddPlayer
	//	*ServerEvent_RemovePlayer
	//	*ServerEvent_Intents
	//	*ServerEvent_State
	//	*ServerEvent_Angle
	//	*ServerEvent_Shoot
	Event isServerEvent_Event `protobuf_oneof:"event"`
}

func (x *ServerEvent) Reset() {
	*x = ServerEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_app_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent) ProtoMessage() {}

func (x *ServerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent.ProtoReflect.Descriptor instead.
func (*ServerEvent) Descriptor() ([]byte, []int) {
	return file_proto_app_proto_rawDescGZIP(), []int{13}
}

func (x *ServerEvent) GetTick() int64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *ServerEvent) GetPlayer() *PlayerDetails {
	if x != nil {
		return x.Player
	}
	return nil
}

func (m *ServerEvent) GetEvent() isServerEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *ServerEvent) GetAddPlayer() *AddPlayer {
	if x, ok := x.GetEvent().(*ServerEvent_AddPlayer); ok {
		return x.AddPlayer
	}
	return nil
}

func (x *ServerEvent) GetRemovePlayer() *RemovePlayer {
	if x, ok := x.GetEvent().(*ServerEvent_RemovePlayer); ok {
		return x.RemovePlayer
	}
	return nil
}

func (x *ServerEvent) GetIntents() *Intents {
	if x, ok := x.GetEvent().(*ServerEvent_Intents); ok {
		return x.Intents
	}
	return nil
}

func (x *ServerEvent) GetState() *StateBuffer {
	if x, ok := x.GetEvent().(*ServerEvent_State); ok {
		return x.State
	}
	return nil
}

func (x *ServerEvent) GetAngle() *Angle {
	if x, ok := x.GetEvent().(*ServerEvent_Angle); ok {
		return x.Angle
	}
	return nil
}

func (x *ServerEvent) GetShoot() *Shoot {
	if x, ok := x.GetEvent().(*ServerEvent_Shoot); ok {
		return x.Shoot
	}
	return nil
}

type isServerEvent_Event interface {
	isServerEvent_Event()
}

type ServerEvent_AddPlayer struct {
	AddPlayer *AddPlayer `protobuf:"bytes,3,opt,name=add_player,json=addPlayer,proto3,oneof"`
}

type ServerEvent_RemovePlayer struct {
	RemovePlayer *RemovePlayer `protobuf:"bytes,4,opt,name=remove_player,json=removePlayer,proto3,oneof"`
}

type ServerEvent_Intents struct {
	Intents *Intents `protobuf:"bytes,5,opt,name=intents,proto3,oneof"`
}

type ServerEvent_State struct {
	State *StateBuffer `protobuf:"bytes,6,opt,name=state,proto3,oneof"`
}

type ServerEvent_Angle struct {
	Angle *Angle `protobuf:"bytes,7,opt,name=angle,proto3,oneof"`
}

type ServerEvent_Shoot struct {
	Shoot *Shoot `protobuf:"bytes,8,opt,name=shoot,proto3,oneof"`
}

func (*ServerEvent_AddPlayer) isServerEvent_Event() {}

func (*ServerEvent_RemovePlayer) isServerEvent_Event() {}

func (*ServerEvent_Intents) isServerEvent_Event() {}

func (*ServerEvent_State) isServerEvent_Event() {}

func (*ServerEvent_Angle) isServerEvent_Event() {}

func (*ServerEvent_Shoot) isServerEvent_Event() {}

var File_proto_app_proto protoreflect.FileDescriptor

var file_proto_app_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x24, 0x0a, 0x06, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x0c, 0x0a, 0x01, 0x78,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x79, 0x22, 0x9c, 0x01, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x23, 0x0a, 0x08, 0x76, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x08, 0x76,
	0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x12, 0x23, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x56, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x07,
	0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e,
	0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x07, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x05, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x22, 0x49, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x69, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74,
	0x69, 0x63, 0x6b, 0x12, 0x2c, 0x0a, 0x0d, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x52, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x73, 0x22, 0x83, 0x01, 0x0a, 0x0b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x42, 0x75, 0x66, 0x66, 0x65,
	0x72, 0x12, 0x1e, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x06, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x73, 0x12, 0x31, 0x0a, 0x0d, 0x66, 0x75, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x0c, 0x66, 0x75, 0x74, 0x75, 0x72, 0x65, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x61, 0x78, 0x5f, 0x63, 0x61, 0x70, 0x61,
	0x63, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x6d, 0x61, 0x78, 0x43,
	0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x22, 0x71, 0x0a, 0x07, 0x49, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x73, 0x12, 0x29, 0x0a, 0x07, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x49, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x3b, 0x0a,
	0x06, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10,
	0x00, 0x12, 0x08, 0x0a, 0x04, 0x4a, 0x55, 0x4d, 0x50, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x4d,
	0x4f, 0x56, 0x45, 0x5f, 0x4c, 0x45, 0x46, 0x54, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x4d, 0x4f,
	0x56, 0x45, 0x5f, 0x52, 0x49, 0x47, 0x48, 0x54, 0x10, 0x03, 0x22, 0x09, 0x0a, 0x07, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x17, 0x0a, 0x05, 0x53, 0x68, 0x6f, 0x6f, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x0b,
	0x0a, 0x09, 0x41, 0x64, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x0e, 0x0a, 0x0c, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x1d, 0x0a, 0x05, 0x41,
	0x6e, 0x67, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x05, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x22, 0x33, 0x0a, 0x0d, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x69, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x69, 0x63, 0x6b, 0x22,
	0xfc, 0x01, 0x0a, 0x0b, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x69, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74,
	0x69, 0x63, 0x6b, 0x12, 0x24, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x48, 0x00,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x24, 0x0a, 0x07, 0x69, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x49, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x73, 0x48, 0x00, 0x52, 0x07, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x12,
	0x34, 0x0a, 0x0d, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x0a, 0x05, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x41, 0x6e, 0x67, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x05,
	0x61, 0x6e, 0x67, 0x6c, 0x65, 0x12, 0x1e, 0x0a, 0x05, 0x73, 0x68, 0x6f, 0x6f, 0x74, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x53, 0x68, 0x6f, 0x6f, 0x74, 0x48, 0x00, 0x52, 0x05,
	0x73, 0x68, 0x6f, 0x6f, 0x74, 0x42, 0x07, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0xc1,
	0x02, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x69, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x69,
	0x63, 0x6b, 0x12, 0x26, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x2b, 0x0a, 0x0a, 0x61, 0x64,
	0x64, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a,
	0x2e, 0x41, 0x64, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x48, 0x00, 0x52, 0x09, 0x61, 0x64,
	0x64, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x34, 0x0a, 0x0d, 0x72, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x48, 0x00, 0x52,
	0x0c, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x24, 0x0a,
	0x07, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x48, 0x00, 0x52, 0x07, 0x69, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x73, 0x12, 0x24, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72,
	0x48, 0x00, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x0a, 0x05, 0x61, 0x6e, 0x67,
	0x6c, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x41, 0x6e, 0x67, 0x6c, 0x65,
	0x48, 0x00, 0x52, 0x05, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x12, 0x1e, 0x0a, 0x05, 0x73, 0x68, 0x6f,
	0x6f, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x53, 0x68, 0x6f, 0x6f, 0x74,
	0x48, 0x00, 0x52, 0x05, 0x73, 0x68, 0x6f, 0x6f, 0x74, 0x42, 0x07, 0x0a, 0x05, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_app_proto_rawDescOnce sync.Once
	file_proto_app_proto_rawDescData = file_proto_app_proto_rawDesc
)

func file_proto_app_proto_rawDescGZIP() []byte {
	file_proto_app_proto_rawDescOnce.Do(func() {
		file_proto_app_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_app_proto_rawDescData)
	})
	return file_proto_app_proto_rawDescData
}

var file_proto_app_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_app_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_app_proto_goTypes = []interface{}{
	(Intents_Intent)(0),   // 0: Intents.Intent
	(*Vector)(nil),        // 1: Vector
	(*Player)(nil),        // 2: Player
	(*State)(nil),         // 3: State
	(*StateBuffer)(nil),   // 4: StateBuffer
	(*Intents)(nil),       // 5: Intents
	(*Connect)(nil),       // 6: Connect
	(*RequestState)(nil),  // 7: RequestState
	(*Shoot)(nil),         // 8: Shoot
	(*AddPlayer)(nil),     // 9: AddPlayer
	(*RemovePlayer)(nil),  // 10: RemovePlayer
	(*Angle)(nil),         // 11: Angle
	(*PlayerDetails)(nil), // 12: PlayerDetails
	(*ClientEvent)(nil),   // 13: ClientEvent
	(*ServerEvent)(nil),   // 14: ServerEvent
}
var file_proto_app_proto_depIdxs = []int32{
	1,  // 0: Player.velocity:type_name -> Vector
	1,  // 1: Player.position:type_name -> Vector
	5,  // 2: Player.intents:type_name -> Intents
	2,  // 3: State.player_states:type_name -> Player
	3,  // 4: StateBuffer.states:type_name -> State
	14, // 5: StateBuffer.future_events:type_name -> ServerEvent
	0,  // 6: Intents.intents:type_name -> Intents.Intent
	6,  // 7: ClientEvent.connect:type_name -> Connect
	5,  // 8: ClientEvent.intents:type_name -> Intents
	7,  // 9: ClientEvent.request_state:type_name -> RequestState
	11, // 10: ClientEvent.angle:type_name -> Angle
	8,  // 11: ClientEvent.shoot:type_name -> Shoot
	12, // 12: ServerEvent.player:type_name -> PlayerDetails
	9,  // 13: ServerEvent.add_player:type_name -> AddPlayer
	10, // 14: ServerEvent.remove_player:type_name -> RemovePlayer
	5,  // 15: ServerEvent.intents:type_name -> Intents
	4,  // 16: ServerEvent.state:type_name -> StateBuffer
	11, // 17: ServerEvent.angle:type_name -> Angle
	8,  // 18: ServerEvent.shoot:type_name -> Shoot
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_proto_app_proto_init() }
func file_proto_app_proto_init() {
	if File_proto_app_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_app_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vector); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_app_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_app_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*State); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_app_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StateBuffer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_app_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Intents); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_app_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Connect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_app_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_app_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Shoot); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_app_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_app_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemovePlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_app_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Angle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_app_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_app_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_app_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_app_proto_msgTypes[12].OneofWrappers = []interface{}{
		(*ClientEvent_Connect)(nil),
		(*ClientEvent_Intents)(nil),
		(*ClientEvent_RequestState)(nil),
		(*ClientEvent_Angle)(nil),
		(*ClientEvent_Shoot)(nil),
	}
	file_proto_app_proto_msgTypes[13].OneofWrappers = []interface{}{
		(*ServerEvent_AddPlayer)(nil),
		(*ServerEvent_RemovePlayer)(nil),
		(*ServerEvent_Intents)(nil),
		(*ServerEvent_State)(nil),
		(*ServerEvent_Angle)(nil),
		(*ServerEvent_Shoot)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_app_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_app_proto_goTypes,
		DependencyIndexes: file_proto_app_proto_depIdxs,
		EnumInfos:         file_proto_app_proto_enumTypes,
		MessageInfos:      file_proto_app_proto_msgTypes,
	}.Build()
	File_proto_app_proto = out.File
	file_proto_app_proto_rawDesc = nil
	file_proto_app_proto_goTypes = nil
	file_proto_app_proto_depIdxs = nil
}
